version: "3.9"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: /home/pptruser
    restart: always
    volumes:
      - .:/home/pptruser
    environment:
      - PORT=${PORT}
      - DB_CONNECTION=postgres
      - TEST=${TEST}

